### ISSUE TITLE
Error regarding Arduino 1.5.5 r2

### ISSUE THREAD

**Issue by muddster** [shirriff/Arduino-IRremote#53]
The IR Receiver program worked fine with the 1.01 IDE but would not compile with 1.5.5 r2
the error was as follows:

C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremoteTools.cpp:5: error: 'TKD2' was not declared in this scope

Any ideas on how to fix this problem?

**Comment by z3t0** [comment]
@muddster This error is not with the IDE version, rather it is with Arduino Software having a library conflict.
Check Issue #98.

The issue is being closed as it has been over 3 months since any activity and there does not seem to be any pending question. If the issue is not solved simply reopen it and label as 'New'.

**Comment by ernawatie** [comment]
i used arduion IDE and pop up this error.. how i need to solve this problem?
C:\Program Files (x86)\Arduino\libraries\IRremote\irISR.cpp:1:27: fatal error: avr/interrupt.h: No such file or directory
 #include <avr/interrupt.h>
                           ^
compilation terminated.
Multiple libraries were found for "IRremote.h"
 Used: C:\Program Files (x86)\Arduino\libraries\IRremote
 Not used: C:\Program Files (x86)\Arduino\libraries\RobotIRremote
Error compiling.

**Comment by z3t0** [comment]
Delete the folder C:\Program Files (x86)\Arduino\libraries\RobotIRremote It is a conflicting library

**Comment by adolfosantana** [comment]
I have the Arduino IDE ver. 1.6.5 but I have a new problem in trying to compile my program. Can you help me on this? Thanks, This is the error messages:


C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremote.cpp:1347:3: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
   long hash = FNV_BASIS_32;
   ^
C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremote.cpp: In member function 'long int IRrecv::decodeWhynter(decode_results*)':
C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremote.cpp:753:51: error: a function-definition is not allowed here before '{' token
 long IRrecv::decodeSharp(decode_results *results) {
                                                   ^
C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremote.cpp:1357:1: error: expected '}' at end of input
 }
 ^
C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremote.cpp:1357:1: error: expected '}' at end of input
C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremote.cpp:1357:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Error compiling.

**Comment by z3t0** [comment]
Please read my comment above. It will solve your problem

**Comment by adolfosantana** [comment]
Thanks for your quick response, but I don't know which comment are you refering to?

Adolfo Santana 
Date: Wed, 12 Aug 2015 19:24:08 -0700

**Comment by z3t0** [comment]
@adolfosantana Haha sorry... wanted to try and be all mystical like a bunch of other people on GitHub :smile:

Anyways... Delete the folder C:\Program Files (x86)\Arduino\libraries\RobotIRremote\ It conflicts with this library.

**Comment by adolfosantana** [comment]
Rafi Khan,I'm trying to run this code to an Arduino car that I bought. See here: http://www.amazon.com/Next-Bluetooth-Controlled-Arduino-Official/dp/B00ORMPC3C/ref=sr_1_6?ie=UTF8&qid=1439509717&sr=8-6&keywords=arduino+car
I did what you told me to do, but I have some other error messages and I don't know what to do next because all the compiling errors are library related.
Here are the code and the error messages.
Thanks for your help.

Adolfo Santana 

Date: Wed, 12 Aug 2015 19:29:58 -0700

**Comment by z3t0** [comment]
You seem to have more than one Servo library. What is inside your Documents/Arduino/ Folder and also what is inside your C:\Program Files\Arduino\libraries folder
